### ISSUE TITLE
Weird behavior of a Web Socket

### ISSUE THREAD

**Issue by 0xDmtri** [zmok-io/zmok-issue-tracker#1]
Hi,

Noticed one bug with a web socket connection. The socket unexpectedly closes when you try to send "eth_GetBlockNumber"  request. Subscriptions work fine tho. 

<img width="1075" alt="Screenshot 2023-06-13 at 2 22 13 AM" src="https://github.com/zmok-io/zmok-issue-tracker/assets/33504992/1305f146-6e3a-4d2c-830c-70dec6c99212">

**Comment by klobusnikpeter** [comment]
Thanks for the report. It seems to require a more thorough investigation. @justcoon will dive into this and get back with an update.

**Comment by justcoon** [comment]
hello @0xDmtri 

in case `eth_GetBlockNumber`, don't  you mean `eth_blockNumber`?

can you try curl or wscat with your app id? Thank you

```
curl -X POST -H 'content-type:application/json' --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' https://api.zmok.io/mainnet/<app_id>

{"jsonrpc":"2.0","id":1,"result":"0x10aab72"}
```

```
% wscat -c wss://api.zmok.io/mainnet/<app_id>
Connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}
< {"jsonrpc":"2.0","id":1,"result":"0x10aab85"}
```

**Comment by 0xDmtri** [comment]
> {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}

Yes, sorry, it was a typo, ofc ```eth_blockNumber```.  And yes, you are right, it is working via wscat. Strangely connection closes with ethers-rs as before. All other nodes work fine with ethers-rs. I will have to have a look into traces I guess. Thanks!
